version: '3'
services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/driveops-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ${DOCKERHUB_USERNAME}/driveops-backend:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - ./uploads:/app/uploads

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
