version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend/api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/car_management
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - ./backend/api/uploads:/app/uploads

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
