name: DriveOps CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Frontend Dependencies
        run: |
          cd Car-Management-main/frontend
          npm install
      - name: Run Frontend Linter
        run: |
          cd Car-Management-main/frontend
          npm run lint || echo "No lint script found, skipping"
  
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Dependencies
        run: |
          cd Car-Management-main/frontend
          npm install
      - name: Build Frontend
        run: |
          cd Car-Management-main/frontend
          npm run build
      - name: Archive Production Build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build
          retention-days: 5
