name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Frontend Dependencies
        run: |
          cd Car-Management-main/frontend
          npm install
      - name: Run Frontend Linter
        run: |
          cd Car-Management-main/frontend
          npm run lint || echo "No lint script found, skipping"
  
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Frontend Dependencies
        run: |
          cd Car-Management-main/frontend
          npm install
      - name: Create Axios Mock
        run: |
          cd Car-Management-main/frontend/src/api
          cat > api.test.js << 'EOF'
          const API = {
            get: jest.fn(),
            post: jest.fn(),
            put: jest.fn(),
            delete: jest.fn(),
            create: jest.fn().mockReturnThis(),
            interceptors: {
              request: { use: jest.fn() },
              response: { use: jest.fn() }
            }
          };
          export default API;
          EOF
      - name: Update Jest Config
        run: |
          cd Car-Management-main/frontend
          cat > jest.config.js << 'EOF'
          module.exports = {
            testEnvironment: 'jsdom',
            moduleNameMapper: {
              "^axios$": "<rootDir>/node_modules/axios/dist/node/axios.cjs",
              "^../api/api$": "<rootDir>/src/api/api.test.js"
            },
            transformIgnorePatterns: [
              "/node_modules/(?!(axios)/)"
            ],
            setupFilesAfterEnv: ['<rootDir>/src/setupTests.js'],
            collectCoverageFrom: [
              "src/**/*.{js,jsx}",
              "!src/index.js",
              "!src/reportWebVitals.js"
            ]
          };
          EOF
      - name: Run Frontend Tests
        run: |
          cd Car-Management-main/frontend
          CI=true npm test -- --passWithNoTests
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: Car-Management-main/frontend/coverage
          retention-days: 5
  
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Dependencies
        run: |
          cd Car-Management-main/frontend
          npm install
      - name: Create nginx config
        run: |
          cd Car-Management-main/frontend
          cat > nginx.conf << 'EOF'
          server {
            listen 80;
            server_name _;
            
            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri $uri/ /index.html;
            }
            
            # Forward API requests to backend
            location /api/ {
                proxy_pass http://backend:5000/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
          }
          EOF
      - name: Build Frontend
        run: |
          cd Car-Management-main/frontend
          npm run build
      - name: Archive Production Build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: Car-Management-main/frontend/build
          retention-days: 5
          
  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Create nginx.conf for Docker
        run: |
          cd Car-Management-main/frontend
          mkdir -p docker-context
          cat > docker-context/nginx.conf << 'EOF'
          server {
            listen 80;
            server_name _;
            
            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri $uri/ /index.html;
            }
            
            # Forward API requests to backend
            location /api/ {
                proxy_pass http://backend:5000/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
          }
          EOF
      - name: Download frontend build
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: Car-Management-main/frontend/docker-context
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./Car-Management-main/frontend
          push: ${{ github.event_name == 'push' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/driveops-frontend:latest
      - name: Create uploads directory for backend
        run: |
          mkdir -p Car-Management-main/backend/api/uploads
          touch Car-Management-main/backend/api/uploads/.gitkeep
      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./Car-Management-main/backend/api
          push: ${{ github.event_name == 'push' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/driveops-backend:latest